### ISSUE TITLE
Warning: No Image Received

### ISSUE THREAD

**Issue by akash-sachan** [appinho/ROS_Perception_Package_Kitti_Dataset#4] opened 2018-09-11 10:06 UTC
I'm using the dataset 2011_09_26 (0001).
RViz opens but there is no output. Map and the 3 images come with the warnings- 
  No Map Received
  No Map Received

What could be the reason?
Also, only the path and the filename had to be taken care of in the launch file right?

**Comment by appinho** [comment] 2018-09-11 12:56
Can you quickly let me know what commands you run in the terminals? That would help me a lot to find a solution

**Comment by akash-sachan** [comment] 2018-09-11 13:06
Exactly like in your readme file except that I downloaded the repository manually. 
Also, I have used kitti2bag previously.
Changed the bag_name and directory in the launch files

**Comment by akash-sachan** [comment] 2018-09-11 13:20
cd Desktop
mkdir -p catkin_ws/src  
cd catkin_ws/src  

"I download the repository"  

cd ..  
catkin_make  
source devel/setup.bash
cd ../kitti_datasets
kitti2bag -t 2011_09_26 -r 0060 raw_synced
mkdir ~/data/0060
mv bag_file_name.bag ~/data/0060/synchronized_data.bag

"I change all the filename and path in all launch files"

cd catkin_ws/src/ROS_Perception_Package_Kitti_Dataset
roslaunch tracking tracking.launch

**Comment by appinho** [comment] 2018-09-12 02:30
Thanks for the description!

First let’s test if the bag file conversion is successful. Therefore, execute following command in the terminal:

rosbag info your_filename.bag

Then you should see a summary about your bag file. Most importantly, in the topics section the images, oxts and pointcloud data should have the same amount of occurrences!

Is this the case for you?

**Comment by akash-sachan** [comment] 2018-09-12 08:03
akash@akash-VirtualBox:~/data/0060$ rosbag info synchronized_data.bag 
path:        synchronized_data.bag
version:     2.0
duration:    8.0s
start:       Sep 26 2011 14:34:42.51 (1317027882.51)
end:         Sep 26 2011 14:34:50.47 (1317027890.47)
size:        406.0 MB
messages:    1092
compression: none [312/312 chunks]
types:       geometry_msgs/TwistStamped [98d34b0043a2093cf9d9345ab6eef12e]
             sensor_msgs/CameraInfo     [c9a58c1b0b154e0e6da7578cb991d214]
             sensor_msgs/Image          [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu            [6a62c6daae103f4ff57a132d6f95cec2]
             sensor_msgs/NavSatFix      [2d3a8cd499b9b4a0249fb98fd05cfa48]
             sensor_msgs/PointCloud2    [1158d486dd51d683ce2f1be655c3c181]
             tf2_msgs/TFMessage         [94810edda583a504dfda3829e70d7eec]
topics:      /kitti/camera_color_left/camera_info    78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_color_left/image_raw      78 msgs    : sensor_msgs/Image         
             /kitti/camera_color_right/camera_info   78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_color_right/image_raw     78 msgs    : sensor_msgs/Image         
             /kitti/camera_gray_left/camera_info     78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_gray_left/image_raw       78 msgs    : sensor_msgs/Image         
             /kitti/camera_gray_right/camera_info    78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_gray_right/image_raw      78 msgs    : sensor_msgs/Image         
             /kitti/oxts/gps/fix                     78 msgs    : sensor_msgs/NavSatFix     
             /kitti/oxts/gps/vel                     78 msgs    : geometry_msgs/TwistStamped
             /kitti/oxts/imu                         78 msgs    : sensor_msgs/Imu           
             /kitti/velo/pointcloud                  78 msgs    : sensor_msgs/PointCloud2   
             /tf                                     78 msgs    : tf2_msgs/TFMessage        
             /tf_static                              78 msgs    : tf2_msgs/TFMessage

**Comment by akash-sachan** [comment] 2018-09-14 09:34
I haven't modified the data set. What seems to be wrong?

**Comment by appinho** [comment] 2018-09-15 09:25
Can you adapt the sensor.launch and run

roslaunch sensor_processing sensor.launch

And check if you see the data there?

**Comment by akash-sachan** [comment] 2018-09-17 05:52
No data there as well

**Comment by appinho** [comment] 2018-09-17 05:58
Ok, one fundamental test then:

Terminal 1: roscore
Terminal 2: rosbag play -l synchronized_data.bag
Terminal 3: rviz

Do you see data then? And do you know how to activate data to be plotted in rviz?

**Comment by akash-sachan** [comment] 2018-09-17 06:21
Yes. It is visible there. I visualized a pointlcloud2. This means that the .bag file is alright. 
Please mention the list of changes the launch files need.

**Comment by akash-sachan** [comment] 2018-09-17 09:12
In
visualization/src/visualization_lib/visualization.cpp 
I had to change the path to my home directory.
Finding more such files. 
Would suggest using '~' instead of '/home/username'
or
Mention all the places where to edit paths

**Comment by akash-sachan** [comment] 2018-09-17 09:29
detection/launch/detection.launch

evaluation/src/evaluation_lib/evaluation.cpp
evaluation/launch/evaluation.launch

sensor_processing/scripts/semantic_segmentation_node.py
sensor_processing/src/sensor_processing_lib/sensor_fusion.cpp
sensor_processing/launch/sensor.launch

tracking/tracking.launch

visualization/src/visualization_lib/visualization.cpp

**Comment by appinho** [comment] 2018-09-17 13:45
Thanks for finding those paths! Would you mind creating a pull request with the path changes since I don’t have access to a Linux pc right now? I would really appreciate it

**Comment by akash-sachan** [comment] 2018-09-18 05:53
Sure. I'll do that once I find all such path issues since it's not working yet

**Comment by wxtshr001** [comment] 2018-09-18 16:42
Hi!
I'm still getting the same issue, after I've corrected all path issues.
When I run sensor.launch alone, the output comes with iterant errors "Error getting latest time from frame 'velo_link' to frame 'velo_link'" as below
This is my output:
...
NODES
  /
    my_rviz (rviz/rviz)
    player (rosbag/play)
    sensor_setup_node (sensor_processing/sensor_setup)

auto-starting new master
process[master]: started with pid [18946]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d6078506-bb5f-11e8-9b4e-40a3cc52b449
process[rosout-1]: started with pid [18959]
started core service [/rosout]
process[player-2]: started with pid [18971]
process[sensor_setup_node-3]: started with pid [18982]
process[my_rviz-4]: started with pid [18989]
[ERROR] [1537288093.413131784]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
[ERROR] [1537288093.441895546]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
[ERROR] [1537288093.467271806]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
[ERROR] [1537288093.498375175]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
[ERROR] [1537288093.532734415]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
[ERROR] [1537288093.564308791]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
[ERROR] [1537288093.596618157]: Error getting latest time from frame 'velo_link' to frame 'velo_link':  (Error code: 1)
...
Can you give me some advise on it? Thanks a lot

**Comment by akash-sachan** [comment] 2018-09-19 05:32
I'm also facing the same problem. @appinho could you suggest what the problem area could be after removing any path related issues?

**Comment by appinho** [comment] 2018-09-19 08:23
I will have a look into the files to see if I can find something quickly. However, I have no laptop with me for the next time to debug it there.
Add me on Skype and we can also arrange a session to fix that issue:

sn0okerchamp

**Comment by wxtshr001** [comment] 2018-09-19 10:44
I've commented the rviz node in sensor.launch, it stopped errors but stuck in 
[ INFO] [1537353126.525288920]: inv_radial_res 4
There is a full rostopic list, but rostopic echo command got nothing with topic /sensor/cloud/*, which works well with /kitti/velo/pointcloud.
I commanded roswtf, it showed information as below:
Online checks summary:

Found 1 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING Received out-of-date/future transforms:
 * receiving transform from [/player] that differed from ROS time by -220334475.07s


Found 1 error(s).

ERROR Different number of openni2 sensors found.
 * 0 openni2 sensors found (expected: 1).

@appinho I hope these can be helpful

**Comment by Haotian-Zhang** [comment] 2018-09-20 04:07
Hi!
I've run all the nodes and got the same errors Please help us to debug it! Thank you so much!

**Comment by appinho** [comment] 2018-09-20 04:57
Add me on Skype please! I don’t have access to a computer. Need to debug it with one of you guys

**Comment by appinho** [comment] 2018-09-20 14:59
Quick update: I could have a small session with @Haotian-Zhang and I have a guess where the error lies:

Can somebody print the time stamps of the left raw images and the velodyne pointcloud by executing:

rostopic echo TOPICNAME/Header/stamp

And see if the time stamps match perfectly or if there is a small difference between them?

Because I remember I wrote a script to sync them. Unfortunately, this script is on my computer and not in the repo

**Comment by akash-sachan** [comment] 2018-09-21 05:50
**rostopic echo /kitti/camera_color_left/image_raw/header/stamp**

secs: 1317027885
nsecs: 301059961

secs: 1317027885
nsecs: 404594898

secs: 1317027885
nsecs: 508074045

secs: 1317027885
nsecs: 611581087

secs: 1317027885
nsecs: 715212106

secs: 1317027885
nsecs: 818723917

secs: 1317027885
nsecs: 922228097

secs: 1317027886
nsecs:  25732040

secs: 1317027886
nsecs: 129364013

secs: 1317027886
nsecs: 232870101

secs: 1317027886
nsecs: 336507081

secs: 1317027886
nsecs: 440009117

secs: 1317027886
nsecs: 543515920

secs: 1317027886
nsecs: 647145986

secs: 1317027886
nsecs: 750664949

secs: 1317027886
nsecs: 854161977

secs: 1317027886
nsecs: 957792043

secs: 1317027887
nsecs:  61305046

secs: 1317027887
nsecs: 164808034

secs: 1317027887
nsecs: 268451929

secs: 1317027887
nsecs: 371942996

secs: 1317027887
nsecs: 475451946

secs: 1317027887
nsecs: 579119920

secs: 1317027887
nsecs: 682593107

secs: 1317027887
nsecs: 786251068

secs: 1317027887
nsecs: 889890909

secs: 1317027887
nsecs: 993361949

secs: 1317027888
nsecs:  96867084

secs: 1317027888
nsecs: 200373888

secs: 1317027888
nsecs: 304016113

**Comment by appinho** [comment] 2018-09-21 14:59
Ok compare these ones with the one of the pointcloud. And I guess they are not identical. That’s why I used a script to make them syncing

**Comment by hiwad-aziz** [comment] 2018-09-21 17:42
@spurs-25 @Haotian-Zhang @wxtshr001 

Since Simon doesn't have access to his computer I tried to reconstruct his sync script:

```
import rosbag
import sys

bag = rosbag.Bag('synchronized_data.bag', 'w')

for topic, msg, t in rosbag.Bag(sys.argv[1]).read_messages():
	if(topic == "/kitti/velo/pointcloud"):
		timestamp = t
	bag.write(topic,msg,timestamp)
bag.close()
```
Save this code as `sync_bagfile.py`, and run it by using `python sync_bagfile.py 'your_kitti_bagfile.bag'`.
I haven't had the time to test the script properly but there shouldn't be any issues. Let me know if this solves your problem.

**Comment by Haotian-Zhang** [comment] 2018-09-21 21:07
Hi @hiwad-aziz ,
After running your script, it outputs this error:

Traceback (most recent call last):
  File "sync_bagfile.py", line 6, in <module>
    for topic, msg, t in rosbag.Bag(sys.argv[1]).read_messages():
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 173, in __init__
    self._open(f, mode, allow_unindexed)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 1102, in _open
    if   mode == 'r': self._open_read(f, allow_unindexed)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 1138, in _open_read
    self._reader.start_reading()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbag/bag.py", line 2312, in start_reading
    raise ROSBagUnindexedException()
rosbag.bag.ROSBagUnindexedException: Unindexed bag

I search for Google and it suggests me to do 'rosbag reindex' first, but that still doesn't work. Please tell me if anything else I can provide you.

**Comment by Haotian-Zhang** [comment] 2018-09-21 21:28
I wrote this script and hope this will be useful,
```
import rosbag
import sys

with rosbag.Bag('synchronized_data.bag', 'w') as outbag:
    for topic, msg, t in rosbag.Bag('kitti_2011_09_26_drive_0060_synced.bag').read_messages():
        # This also replaces tf timestamps under the assumption 
        # that all transforms in the message share the same timestamp
        if topic == "/kitti/velo/pointcloud":
        	timestamp = t
        outbag.write(topic, msg, timestamp)
outbag.close()
```

**Comment by hiwad-aziz** [comment] 2018-09-22 08:49
@Haotian-Zhang I tested the script and it works fine for me (on the same scenario).
Maybe @spurs-25 has time to test it as well and report back?

**Comment by Haotian-Zhang** [comment] 2018-09-22 08:54
@hiwad-aziz Thank you, I successfully did the time synchronization. However, I still cannot get the velo output in the rviz. Could you please help us further debug into the problem?

**Comment by hiwad-aziz** [comment] 2018-09-22 18:47
@Haotian-Zhang 
 @appinho and I resolved the problem and I created a pull request to add the synchronization script to the repo. It should work properly once the pull request has been merged.

**Comment by Haotian-Zhang** [comment] 2018-09-22 20:28
@appinho @hiwad-aziz Thank you so much for your help! I will try to run the codes as soon as possible and see if it works on my computer!

**Comment by akash-sachan** [comment] 2018-09-23 11:58
Great work! 
I'll only be able to run it on my computer tomorrow :(

**Comment by spurs-25** [comment] 2018-09-24 06:45
[FATAL] [1537689857.981391980]: Error opening file: ~/kitti_data/0060/synchronized_data.bag

**Comment by akash-sachan** [comment] 2018-09-24 08:08
Hey. Can someone please share their segmented semantic images folder?

**Comment by hiwad-aziz** [comment] 2018-09-24 08:23
@spurs-25 check this out, if you have a CUDA-enabled GPU: https://github.com/hiwad-aziz/kitti_deeplab

**Comment by akash-sachan** [comment] 2018-09-24 08:27
Thanks @hiwad-aziz . I'm trying to use your repo but I don't have a GPU. For the moment, I just want to check if this ROS Perception package is working on my PC. Could you share your segmented images for the 0060 set?

**Comment by hiwad-aziz** [comment] 2018-09-24 08:41
@spurs-25 Here you go: https://drive.google.com/open?id=1ihGnk5x9OlzF4X-YJXFsKB8rYSLyo0YF

**Comment by spurs-25** [comment] 2018-09-24 09:33
Thanks. Still facing this error
[FATAL] [1537699420.168805747]: Error opening file: ~/kitti_data/0060/synchronized_data.bag

**Comment by appinho** [comment] 2018-09-24 12:17
Is it working now @spurs-25 ? If not, double check the paths. If it is not working even then, please let me know

**Comment by liaojiacai** [comment] 2018-09-25 07:03
@appinho 
I met a problem，the error is:
[FATAL] [1537857863.839548743]: Error opening file: ~/kitti_data/0060/synchronized_data.bag
but I have been put the rosbag under this path.
After using the command: "rosbag info synchronized_data.bag ",the output are:
path:        synchronized_data.bag
version:     2.0
duration:    8.0s
start:       Sep 26 2011 14:34:42.49 (1317018882.49)
end:         Sep 26 2011 14:34:50.47 (1317018890.47)
size:        406.3 MB
messages:    1482
compression: none [313/313 chunks]
types:       geometry_msgs/TwistStamped [98d34b0043a2093cf9d9345ab6eef12e]
             sensor_msgs/CameraInfo     [c9a58c1b0b154e0e6da7578cb991d214]
             sensor_msgs/Image          [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu            [6a62c6daae103f4ff57a132d6f95cec2]
             sensor_msgs/NavSatFix      [2d3a8cd499b9b4a0249fb98fd05cfa48]
             sensor_msgs/PointCloud2    [1158d486dd51d683ce2f1be655c3c181]
             tf2_msgs/TFMessage         [94810edda583a504dfda3829e70d7eec]
topics:      /kitti/camera_color_left/camera_info     78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_color_left/image_raw       78 msgs    : sensor_msgs/Image         
             /kitti/camera_color_right/camera_info    78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_color_right/image_raw      78 msgs    : sensor_msgs/Image         
             /kitti/camera_gray_left/camera_info      78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_gray_left/image_raw        78 msgs    : sensor_msgs/Image         
             /kitti/camera_gray_right/camera_info     78 msgs    : sensor_msgs/CameraInfo    
             /kitti/camera_gray_right/image_raw       78 msgs    : sensor_msgs/Image         
             /kitti/oxts/gps/fix                      78 msgs    : sensor_msgs/NavSatFix     
             /kitti/oxts/gps/vel                      78 msgs    : geometry_msgs/TwistStamped
             /kitti/oxts/imu                          78 msgs    : sensor_msgs/Imu           
             /kitti/velo/pointcloud                   78 msgs    : sensor_msgs/PointCloud2   
             /tf                                      78 msgs    : tf2_msgs/TFMessage        
             /tf_static                              468 msgs    : tf2_msgs/TFMessage

Is there any question? I have checked all files that related to the rosbag path. I found a path error in the file of  /tracking/launch/tracking.launch, it must be "~/kitti_data/",not "~/data/",if the rosbag path in other file is"~/kitti_data/". After motified the path, the error is still exist. Please help, Thanks.

**Comment by hiwad-aziz** [comment] 2018-09-25 07:46
@spurs-25 @liaojiacai what I found is that relative paths like "~/..." don't work for me. Try an absolute path like "/home/user/kitti_data/".

**Comment by liaojiacai** [comment] 2018-09-25 08:08
@hiwad-aziz Great，it works. Thank you. Maybe, the "~"is only work well in the shell.

**Comment by yileichen123** [comment] 2018-11-04 11:31
I have followed all the above, but I can't  there is still no image,no map and no tf data,why?

**Comment by appinho** [comment] 2018-11-04 12:01
@yileichen123 have you followed the instructions of the read me?

And do you see any data in rviz?

It helps if you explain your problem more in detail

**Comment by yileichen123** [comment] 2018-11-04 12:12
I can only run the synchronized_data.bag in the rviz, but there is no image like the gif you show in the readme. I have followed all the instructions. like this ,when l run 
roslaunch tracking tracking.launch
rosbag play -r 0.25 synchronized_data.bag
![2018-11-04 20-07-27](https://user-images.githubusercontent.com/37318400/47963904-53653980-e06d-11e8-8625-f8c128c4688e.png)
 
But as I run roslaunch sensor_processing sensor.launch
there is also the error 
![2018-11-04 20-11-48](https://user-images.githubusercontent.com/37318400/47963934-e9995f80-e06d-11e8-9a67-52e31ef16ee8.png)

**Comment by appinho** [comment] 2018-11-04 12:24
1) Try to open the tap Global options in the top right corner of rviz and change the coordinate system 

2) start rviz on your own and try to manually add the data you want to see

Let me know if any of this works for you

**Comment by yileichen123** [comment] 2018-11-04 12:57
Yes, It works. But I still can't see the image as gif1. It seems that I can't upload the result after semantic segmentated.
![2018-11-04 20-49-44](https://user-images.githubusercontent.com/37318400/47964375-210b0a80-e074-11e8-82b0-0c47daa386c9.png)
![2018-11-04 20-55-33](https://user-images.githubusercontent.com/37318400/47964376-210b0a80-e074-11e8-9b9c-98c4e7da159e.png)

**Comment by appinho** [comment] 2018-11-04 13:01
Awesome that is works now 😊

The gif is just a video that fades from the semantic image to the tracking result. 

However, you can visualize the semantic image by adding it to the visualization on your own. Let me know if you need help for this

**Comment by yileichen123** [comment] 2018-11-04 13:05
What's the path of the segmented images like the following? I have set it as the readme.
![0000000001](https://user-images.githubusercontent.com/37318400/47964454-5f54f980-e075-11e8-8ddb-2cc75f48ffd4.png)

**Comment by appinho** [comment] 2018-11-04 14:59
![45bbcd4f-4f76-4737-8945-3e046d3efa91](https://user-images.githubusercontent.com/19282091/47965705-be6a3c80-e07c-11e8-83bd-1417a187b825.jpeg)

This is the code for deploying the pictures!
Add a print command there and check if this method is executed for your case if you still can’t see the images

**Comment by appinho** [comment] 2018-11-07 13:45
@yileichen123 any news? Maybe also the last comment in issue #9 helps you!

**Closed as completed** 2018-11-09 15:10 UTC

**Comment by canihaveaname** [comment] 2022-03-08 14:28
Hello, I ran according to the operation in the readme, but the picture could not be displayed. I downloaded 0012.zip. Does the picture information need to be downloaded separately? I just started learning this field, can you please help me out 


[ WARN] [1646748554.890493462]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748554.894613255]: Empty semantic point cloud!
[ WARN] [1646748555.400600677]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748555.404701194]: Empty semantic point cloud!
[ WARN] [1646748555.923053514]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748555.927108425]: Empty semantic point cloud!
[ WARN] [1646748556.439107921]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748556.443300419]: Empty semantic point cloud!
[ WARN] [1646748556.961663497]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748556.965640884]: Empty semantic point cloud!
[ WARN] [1646748557.478409474]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748557.482468366]: Empty semantic point cloud!
[ WARN] [1646748557.997741672]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748558.001720665]: Empty semantic point cloud!
[ WARN] [1646748558.511803933]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748558.515771263]: Empty semantic point cloud!
[ WARN] [1646748559.034038873]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748559.038129333]: Empty semantic point cloud!
[ WARN] [1646748559.544194778]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748559.548134172]: Empty semantic point cloud!

**Comment by yileichen123** [comment] 2022-03-08 14:29
已收到！

**Comment by canihaveaname** [comment] 2022-03-14 16:15
Can you help me list the files and steps to be downloaded for reproduction? I just started learning, and many of them are not very clear

**Comment by canihaveaname** [comment] 2022-03-14 16:31
The drive I provided from readme 0012 is downloaded from goose's address Zip, which only contains 0012 Bag file. After running roslaunch, the following results appear:
[ WARN] [1646748554.890493462]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748554.894613255]: Empty semantic point cloud!
[ WARN] [1646748555.400600677]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748555.404701194]: Empty semantic point cloud!
[ WARN] [1646748555.923053514]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748555.927108425]: Empty semantic point cloud!
[ WARN] [1646748556.439107921]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748556.443300419]: Empty semantic point cloud!
[ WARN] [1646748556.961663497]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748556.965640884]: Empty semantic point cloud!
[ WARN] [1646748557.478409474]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748557.482468366]: Empty semantic point cloud!
[ WARN] [1646748557.997741672]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748558.001720665]: Empty semantic point cloud!
[ WARN] [1646748558.511803933]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748558.515771263]: Empty semantic point cloud!
[ WARN] [1646748559.034038873]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748559.038129333]: Empty semantic point cloud!
[ WARN] [1646748559.544194778]: Hardcode path in sensor_fusion.cpp processImage()!
[ WARN] [1646748559.548134172]: Empty semantic point cloud!

Do you have any other files to download, or do I need to do some other work? Please help me list a detailed reproduction process, the files I need to download and the work I need to complete. I'm just beginning to learn this field. Thank you very much for your help
